name: Basic tests

on: [push]

jobs:
  smoke-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
    - name: Git clone
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install dotfiles
      run: bash -c './.res/dfm install && source ~/.bashrc'
      env:
        SHELL: bash

    - name: Smoke test vim
      run: timeout 5 vim -c 'redir! > ~/vim_err.log' -c 'redir END | qa!'

    - name: Print Output
      run: bash -c 'test -e ~/vim_err.log && cat ~/vim_err.log; true'

    - name: Check Output 1
      run: bash -c 'test -e ~/vim_err.log && ! grep -P "^E\d*:" ~/vim_err.log; true'

    - name: Check Output
      run: bash -c 'test -e ~/vim_err.log && ! grep -iP "^Error" ~/vim_err.log; true'
