name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install dotfiles
      run: bash -c 'bin/dfm install && source ~/.bashrc'
      env:
        SHELL: bash


    - name: Install vim plugins
      run: vim -c 'redir > ~/vim_err.log' -c 'PluginUpdate' -c 'redir END' -c 'qa!'

    - name: Check Output
      run: ! grep -P '^E\d*:' ~/vim_err.log
